# Generated by Django 3.1.4 on 2020-12-13 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected', models.FloatField()),
                ('actual', models.FloatField()),
            ],
            options={
                'db_table': 'results_table',
            },
        ),
    ]
