# Generated by Django 3.1.4 on 2020-12-05 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('year', models.IntegerField(default=2020)),
                ('is_holiday', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dim_date_table',
            },
        ),
        migrations.CreateModel(
            name='FactReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('stars', models.IntegerField()),
                ('useful', models.IntegerField()),
                ('funny', models.IntegerField()),
                ('cool', models.IntegerField()),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yelp_reviews.dimdate')),
            ],
            options={
                'db_table': 'fact_review_table',
            },
        ),
    ]
